-- AlterTable
ALTER TABLE "FotoRegistro" ADD COLUMN "latInicial" DOUBLE PRECISION,
ADD COLUMN "lngInicial" DOUBLE PRECISION,
ADD COLUMN "latFinal" DOUBLE PRECISION,
ADD COLUMN "lngFinal" DOUBLE PRECISION;
