-- CreateEnum
CREATE TYPE "Cargo" AS ENUM ('TECNICO', 'ALMACENISTA');

-- AlterTable
ALTER TABLE "User" ADD COLUMN "cargo" "Cargo" NOT NULL DEFAULT 'TECNICO';
ALTER TABLE "User" ADD COLUMN "filtroEquipo" TEXT NOT NULL DEFAULT 'TODOS';
